site_name: Neptune's Corner

# Default theme is fucking ugly
theme:
  name: material
  palette:
    scheme: slate

  features:
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - meta
  - blog
  - search
