site_name: Neptune's Corner

# Default theme is fucking ugly
theme:
  name: material
  palette:
    primary: orange
    scheme: slate

  features:
    - navigation.footer
    - navigation.indexes
    - search.suggest

  theme:
    logo: material/weather-tornado
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - meta
  - blog
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/neptunethefox
