authors:
  neptune:
    name: Neptune
    description: Site Owner
    avatar: https://github.com/neptunethefox.png
    
  anon:
    name: Anon
    description: Asked to remain anonymous
    avatar: https://github.com/ghost.png